language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm

env:
  matrix:
    - MAGENTO_VERSION=magento-ce-1.9.1.0
    - MAGENTO_VERSION=magento-ce-1.8.1.0
    - MAGENTO_VERSION=magento-ce-1.7.0.2

before_script:
  - pear install PHP_CodeSniffer
  - phpenv rehash
  - composer self-update
  - composer install --no-interaction
  - phpcs --config-set ignore_warnings_on_exit 1
  - sed -i 's/curl/banan/g' vendor/magento-ecg/coding-standard/Ecg/Sniffs/Security/ForbiddenFunctionSniff.php
  - composer self-update
script:
  - php vendor/bin/parallel-lint --exclude vendor .
  - phpcs --standard=vendor/magento-ecg/coding-standard/Ecg,vendor/mygento/coding-standard/Mygento-Mage1 --ignore=lib .
  - php vendor/bin/phpcpd --exclude=vendor .
  - php vendor/bin/phpdcd --exclude=vendor .
  - php vendor/bin/phpmd . text codesize --exclude vendor
  - curl -sSL https://raw.githubusercontent.com/mygento/hamster/master/setup.sh | bash
