language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  matrix:
    - MAGENTO_VERSION=magento-ce-1.9.1.0
    - MAGENTO_VERSION=magento-ce-1.8.1.0
    - MAGENTO_VERSION=magento-ce-1.7.0.2

before_script:
  - composer self-update
script:
   - curl -sSL https://raw.githubusercontent.com/mygento/hamster/master/setup.sh | bash
